name: Update README TOC

on:
  push:
    branches: [main]
    paths:
      - 'README.md'

permissions:
  contents: write

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README.md
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
